version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: django_user
      POSTGRES_PASSWORD: django_password
      POSTGRES_DB: django_db
    volumes:
      - ./DB:/var/lib/postgresql/data
    networks:
      - db_network

  main_service:
    build:
      context: ./django_service/main_service
      dockerfile: Dockerfile
    container_name: main_service
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - '8001:8000'
    volumes:
      - ./django_service/main_service:/usr/src/app
    depends_on:
      - postgres
    networks:
      - django_network
    environment:
      - DEBUG=True
      - DATABASE_URL=postgres://django_user:django_password@postgres_db:5432/django_db

  user_service:
    build:
      context: ./django_service/user_service
      dockerfile: Dockerfile
    container_name: user_service
    command: python manage.py grpcrunserver --dev
    volumes:
      - ./django_service/user_service:/usr/src/app
    depends_on:
      - postgres
    networks:
      - django_network
      - db_network
    environment:
      - DEBUG=True
      - DATABASE_URL=postgres://django_user:django_password@postgres_db:5432/django_db

  stat_service:
    build:
      context: ./django_service/stat_service
      dockerfile: Dockerfile
    container_name: stat_service
    command: python manage.py grpcrunserver --dev
    volumes:
      - ./django_service/stat_service:/usr/src/app
    depends_on:
      - postgres
    networks:
      - django_network
      - db_network
    environment:
      - DEBUG=True
      - DATABASE_URL=postgres://django_user:django_password@postgres_db:5432/django_db
  game_service:
    build:
      context: ./django_service/game_service
      dockerfile: Dockerfile
    container_name: game_service
    command: python manage.py grpcrunserver --dev
    volumes:
      - ./django_service/game_service:/usr/src/app
    depends_on:
      - postgres
    networks:
      - django_network
      - db_network
    environment:
      - DEBUG=True
      - DATABASE_URL=postgres://django_user:django_password@postgres_db:5432/django_db
  chat_service:
    build:
      context: ./django_service/chat_service
      dockerfile: Dockerfile
    container_name: chat_service
    command: python manage.py grpcrunserver --dev
    volumes:
      - ./django_service/chat_service:/usr/src/app
    depends_on:
      - postgres
    networks:
      - django_network
      - db_network
    environment:
      - DEBUG=True
      - DATABASE_URL=postgres://django_user:django_password@postgres_db:5432/django_db

networks:
  django_network:
  db_network: